name: Publish Docker image to GCR

on:
  workflow_dispatch:

env:
  SERVICE_NAME: ${{ github.event.repository.name }}
  GCR_REGISTRY: us.gcr.io
  GOOGLE_PROJECT: broad-dsp-gcr-public

jobs:
  publish-docker-job:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          # Centralized in dsp-tools-k8s; ask in #dsp-devops-champions for help troubleshooting
          workload_identity_provider: 'projects/1038484894585/locations/global/workloadIdentityPools/github-wi-pool/providers/github-wi-provider'
          service_account: 'dsp-tools-iap-access@dsp-tools-k8s.iam.gserviceaccount.com'

      - name: Explicitly auth Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Construct GCR docker image name
        id: gcr-image-name
        run: echo "name=${GCR_REGISTRY}/${GOOGLE_PROJECT}/${SERVICE_NAME}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: | 
          docker build . -t ${{ steps.gcr-image-name.outputs.name }}:latest
          docker push ${{ steps.gcr-image-name.outputs.name }}:latest
        
      - name: Build and push Docker image (non-develop)
        if: ${{ github.ref != 'refs/heads/develop' }}
        run: | 
            docker build . -t ${{ steps.gcr-image-name.outputs.name }}:$(git rev-parse --short HEAD)-${{ github.ref_name }}
            docker push ${{ steps.gcr-image-name.outputs.name }}:$(git rev-parse --short HEAD)-${{ github.ref_name }}
