name: Publish Docker image to GCR

on:
  workflow_dispatch:

env:
  SERVICE_NAME: ${{ github.event.repository.name }}
  GCR_REGISTRY: us.gcr.io
  GOOGLE_PROJECT: broad-dsp-gcr-public

jobs:
  publish-docker-job:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Auth to GCR
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.GCR_PUBLISH_EMAIL }}
          service_account_key: ${{ secrets.GCR_PUBLISH_KEY_B64 }}

      - name: Explicitly auth Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Construct GCR docker image name
        id: gcr-image-name
        run: echo "name=${GCR_REGISTRY}/${GOOGLE_PROJECT}/${SERVICE_NAME}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: | 
          docker build . -t ${{ steps.gcr-image-name.outputs.name }}:latest
          docker push ${{ steps.gcr-image-name.outputs.name }}:latest
        
      - name: Build and push Docker image (non-develop)
        if: ${{ github.ref != 'refs/heads/develop' }}
        run: | 
            docker build . -t ${{ steps.gcr-image-name.outputs.name }}:$(git rev-parse --short HEAD)-${{ github.ref }}
            docker push ${{ steps.gcr-image-name.outputs.name }}:$(git rev-parse --short HEAD)-${{ github.ref }}
